import React from 'react';

const Terms = () => {
  return(
    <section className="footerPage">
      <div className="pageHeader">
        <h3>Terms of Use</h3>
      </div>
      <div className="content terms">
        <p>These Terms of Use ("Terms of Use") explain a contractual agreement between you ("you," "your") and BluePlans, Inc. dba BluePlattr ("BluePlattr," "we," "us," "our"), regarding your use of this website (the "BluePlattr Website").</p>
        <p>You should print a copy of these Terms of Use for your records. Please note, however, that these Terms of Use may be updated and amended by us from time to time as provided herein and we have no obligation to notify you directly but will instead post any such updates and amendments to this web page.</p>
        <h5>1. AGREEMENT TO TERMS OF USE</h5>
        <p>By using the BluePlattr Website, you agree to these Terms of Use as amended by us from time to time. Furthermore, when you access the BluePlattr Website, you specifically acknowledge your agreement with the most current version of these Terms of Use.</p>
        <h5>2. CHANGE TO TERMS OF USE</h5>
        <p>We reserve the right, at our discretion, to change, modify, add, or remove any portion or all of these Terms of Use at any time. Please check these Terms of Use periodically for changes. Your continued use of the BluePlattr Website after the posting of changes to these Terms of Use will mean you agree to those changes. Any amendments to these Terms of Use by you must be agreed to by us in writing.</p>
        <h5>3. OWNERSHIP OF CONTENT</h5>
        <p>The BluePlattr Website and the content accessible through the BluePlattr Website, and all intellectual property rights included in or associated with the BluePlattr Website, including but not limited to patents, copyrights, trademarks and service marks, including without limitation BluePlans Inc. (collectively, "Content"), are owned or licensed by us, and all right, title and interest in and to the BluePlattr Website and Content remains with BluePlattr. Except as may occur when material is downloaded to your computer in the ordinary course of accessing the BluePlattr Website, material from the BluePlattr Website may not be copied, distributed, re-published, uploaded, posted, modified, reverse engineered, or transmitted in any manner without our prior written consent. Certain Content may be licensed from third parties and all such third-party content and intellectual property rights (including any trademarks or service marks) related to such content belong to the respective third parties. In all events, you may not remove any copyright, trademark or other intellectual property or proprietary notice or legend contained on the BluePlattr Website or in the Content.</p>
        <h5>4. DISCLAIMER OF WARRANTIES</h5>
        <p>BY USING THE BLUEPLATTR WEBSITE, YOU AGREE THAT YOU RECEIVE THE BLUEPLATTR WEBSITE AT YOUR OWN RISK. THE BLUEPLATTR WEBSITE IS PROVIDED "AS IS," WHERE IS, WITH ALL FAULTS AND WITHOUT ANY WARRANTY OR CONDITION OF ANY KIND, EXPRESS, IMPLIED OR STATUTORY. THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORTS IS WITH YOU. WE SPECIFICALLY DISCLAIM THE IMPLIED WARRANTIES OF FITNESS FOR PARTICULAR PURPOSE, MERCHANTABILITY, QUALITY, ACCURACY OR TITLE. FURTHERMORE, THERE IS NO WARRANTY AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE BLUEPLATTR WEBSITE OR AGAINST INFRINGEMENT. We do not guarantee uninterrupted or secure access to the BluePlattr Website, that defects will be corrected, or that the BluePlattr Website or the servers that make it available are free of viruses or other harmful components.</p>
        <h5>5. LIMITATION OF LIABILITY</h5>
        <p>We are a service provider; we are not responsible for any loss or injury whatsoever due to the use of the BluePlattr Website, the Content or other information published through the BluePlattr Website. The BluePlattr Website may be unavailable due to maintenance or other reasons and we will have no liability for any such unavailability. We will also not have any liability for any loss of data, degraded data, old or out-dated data, or errors in data resulting from non-deliveries, mis-deliveries or service interruptions caused by us, any third-party acts or any other web host provider or the Internet infrastructure and network external to the BluePlattr Website. The limitations of liability contained in these Terms of Use inure to our benefit and to the benefit of our affiliates, and to all of our respective shareholders, officers, directors, employees, attorneys and agents. IN NO EVENT SHALL BLUEPLATTR BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES, OR FOR ANY LOSS OF PROFITS OR REVENUE, REGARDLESS OF WHETHER WE KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES, AND IN NO EVENT SHALL OUR TOTAL CUMULATIVE LIABILITY UNDER THIS AGREEMENT EXCEED $100.00. Some jurisdictions do not allow excluding or limiting implied warranties or limiting liability for incidental or consequential damages, and some jurisdictions have special statutory consumer protection provisions which may supersede the foregoing disclaimers and limitations. As a result, these disclaimers and/or limitations may not apply to you if prohibited by law.</p>
        <h5>6. TERMINATION</h5>
        <p>In the event that you violate any of the provisions of these Terms of Use, we may terminate your access to the BluePlattr Website immediately and without prior notice, and you agree that we shall not be liable to you or any third-party for any such termination.</p>
        <h5>7. PROHIBITED ACTIVITIES</h5>
        <p>You may not use any device, software or routine, including but not limited to any viruses, trojan horses, worms, time bombs or other malicious code, intended to damage or interfere with the proper working of the BluePlattr Website or to surreptitiously intercept or expropriate any system, data or personal information from the BluePlattr Website. You may not take any action which imposes an unreasonable or disproportionately large load on our infrastructure, including but not limited to denial of service attacks, "spam" or any other such unsolicited overload technique. You may not use the BluePlattr Website as a service bureau for third parties.</p>
        <h5>8. LINKING AND THIRD-PARTY CONTENT</h5>
        <p>The BluePlattr Website may contain links to third-party websites not under our control or operation. We provide any such links only as a convenience and do not endorse and are not responsible for the contents of any linked site or any link contained in a linked site. Use of any third-party content contained on or accessed from the BluePlattr Website may be conditioned upon terms and conditions as provided by such third-party providers.</p>
        <h5>9. LAWS AND REGULATIONS</h5>
        <p>You must comply with all applicable laws, statutes and regulations regarding: (i) use of the BluePlattr Website and (ii) release of information to and retrieval of information from the BluePlattr Website.</p>
        <h5>10. INDEMNIFICATION</h5>
        <p>You agree to indemnify, defend and hold us harmless from and against any and all claims, demands, actions, costs, liabilities, losses and damages of any kind (including attorneys' fees) resulting from: (i) your use of the BluePlattr Website; (ii) your breach of any provision of these Terms of Use; (iii) the illegality, reliability, appropriateness, originality or copyright of any submission to BluePlattr; and/or (iv) any intentional wrongdoing by you.</p>
        <h5>11. ASSIGNMENT</h5>
        <p>You will not have the right to assign or transfer your rights under these Terms of Use to any other person or entity without our prior written consent, which consent may be withheld for any reason or for no reason. Furthermore, you acknowledge and agree that your access to and use of the BluePlattr Website may not be sublicensed or otherwise transferred voluntarily or by operation of law to any third party. Any attempted assignment, license, sublicense or transfer by you, whether voluntary or involuntary, is void and grounds for termination of your rights under these Terms of Use.</p>
        <h5>12. GOVERNING LAW, ARBITRATION AND JURISDICTION</h5>
        <p>You recognize that although the Internet can be accessed from anywhere in the world, the BluePlattr Website is located in the State of New York, United States of America, and that when you access the BluePlattr Website, you are doing so in the State of New York, United States of America. These Terms of Use shall be governed by and construed in accordance with the internal substantive laws of the State of New York without giving effect to any principles of conflict of law and the federal laws of the United States of America. ANY CONTROVERSY OR CLAIM ARISING OUT OF OR RELATING TO THIS CONTRACT, OR THE BREACH THEREOF, SHALL BE SETTLED BY ARBITRATION ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION UNDER ITS COMMERCIAL ARBITRATION RULES, AND JUDGMENT ON THE AWARD RENDERED BY THE ARBITRATOR(S) MAY BE ENTERED IN ANY COURT HAVING JURISDICTION THEREOF. YOU FURTHER AGREE THAT ANY ARBITRATION ACTION BROUGHT BY YOU ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR THE BLUEPLATTR WEBSITE SHALL BE FILED ONLY IN KINGS COUNTY, NEW YORK, AND YOU HEREBY CONSENT AND SUBMIT TO THE EXCLUSIVE PERSONAL JURISDICTION AND VENUE IN KINGS COUNTY, NEW YORK.</p>
        <h5>13. PRIVACY POLICY</h5>
        <p>By agreeing to these Terms of Use, you also agree to our Privacy Policy located at http://www.blueplattr.com/privacy-policy which is incorporated herein by reference. The Privacy Policy is subject to change from time to time. Your acceptance of these Terms of Use and/or continued use of the BluePlattr Website constitutes your acceptance to any changes to the Privacy Policy.</p>
        <h5>14. MISCELLANEOUS</h5>
        <p>Headings are for reference purposes only. Our failure to exercise or enforce any right or provision of the Terms of Use shall not constitute a waiver of such right or provision. If any provision of these Terms of Use shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms of Use and shall not affect the validity and enforceability of any remaining provisions. Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable materials. Specifically, you agree to comply with all applicable laws regarding the transmission of technical or other data exported from the United States or the country in which you reside. These Terms of Use, and any web pages or other documents incorporated by reference, set forth the entire understanding and agreement between us with respect to the subject matter hereof. BY USING THE BLUEPLATTR WEBSITE AND/OR ACKNOWLEDGING ACCEPTANCE OF THESE TERMS OF USE AT VARIOUS TIMES ON THE BLUEPLATTR WEBSITE OR AS OTHERWISE SET FORTH HEREIN, YOU ACCEPT AND AGREE TO THESE TERMS OF USE.</p>
        <h5>15. CONTACT</h5>
        <p>If you have any problems, questions or complaints about these Terms of Use or the BluePlattr Website, please contact us by email at support@blueplattr.com.</p>
      </div>
    </section>
  );
}

export default Terms